package com.blaubalu.detoxrank.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF004DEA)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDCE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001551)
val md_theme_light_secondary = Color(0xFF006687)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC0E8FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001E2B)
val md_theme_light_tertiary = Color(0xFF296C00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF92FC5D)
val md_theme_light_onTertiaryContainer = Color(0xFF072100)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFCFF)
val md_theme_light_onBackground = Color(0xFF001F2A)
val md_theme_light_surface = Color(0xFFFAFCFF)
val md_theme_light_onSurface = Color(0xFF001F2A)
val md_theme_light_surfaceVariant = Color(0xFFE2E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF45464F)
val md_theme_light_outline = Color(0xFF767680)
val md_theme_light_inverseOnSurface = Color(0xFFE1F4FF)
val md_theme_light_inverseSurface = Color(0xFF003547)
val md_theme_light_inversePrimary = Color(0xFFB7C4FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF004DEA)
val md_theme_light_outlineVariant = Color(0xFFC6C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB7C4FF)
val md_theme_dark_onPrimary = Color(0xFF002681)
val md_theme_dark_primaryContainer = Color(0xFF0039B4)
val md_theme_dark_onPrimaryContainer = Color(0xFFDCE1FF)
val md_theme_dark_secondary = Color(0xFF72D2FF)
val md_theme_dark_onSecondary = Color(0xFF003548)
val md_theme_dark_secondaryContainer = Color(0xFF004D66)
val md_theme_dark_onSecondaryContainer = Color(0xFFC0E8FF)
val md_theme_dark_tertiary = Color(0xFF77DE43)
val md_theme_dark_onTertiary = Color(0xFF123800)
val md_theme_dark_tertiaryContainer = Color(0xFF1D5200)
val md_theme_dark_onTertiaryContainer = Color(0xFF92FC5D)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F2A)
val md_theme_dark_onBackground = Color(0xFFBFE9FF)
val md_theme_dark_surface = Color(0xFF001F2A)
val md_theme_dark_onSurface = Color(0xFFBFE9FF)
val md_theme_dark_surfaceVariant = Color(0xFF45464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C5D0)
val md_theme_dark_outline = Color(0xFF90909A)
val md_theme_dark_inverseOnSurface = Color(0xFF001F2A)
val md_theme_dark_inverseSurface = Color(0xFFBFE9FF)
val md_theme_dark_inversePrimary = Color(0xFF004DEA)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB7C4FF)
val md_theme_dark_outlineVariant = Color(0xFF45464F)
val md_theme_dark_scrim = Color(0xFF000000)

val rank_color = Color(0xFFFFC000)
val rank_color_shade = Color(0xFFFFCA25)
val rank_color_ultra_light = Color(0xFFFFE081)
val rank_color_light = Color(0xFFBB8E04)
val rank_color_ultra_dark = Color(0xFF836918)
val timer_color_dark = Color(0xfffa5443)

val common_green = Color(0xFF2D7910)
val rare_blue = Color(0xFF4477DD)
val rarer_blue = Color(0xFF3943FF)
val epic_purple = Color(0xFFA91EF5)
val very_epic_magenta = Color(0xFFCB04DA)
val legendary_orange = Color(0xFFE78216)

val common_green_toned_down = Color(0xFF607757)
val rare_blue_toned_down = Color(0xFF8DA3CC)
val rarer_blue_toned_down = Color(0xFF9AA0FF)
val epic_purple_toned_down = Color(0xFFD497F5)
val very_epic_magenta_toned_down = Color(0xFFC270C9)
val legendary_orange_toned_down = Color(0xFFDF9F5B)

val md_theme_light_tertiaryContainerVariant = Color(0xFFBFFFA0)


val seed = Color(0xFF004FF0)
